# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66597016a2cccad4fea20512b73cc5585e5227a08c452d4161897be9ea284f5ead17c20badd67ae46d4aed02e3a80a981099011dadd4db212ff3ae37ed749be8

test:
  secret_key_base: 989789fb25f85b92a43169fc98e37619a4e95e43145817d172ed41571b6f691188a480500f354c648449b1fc488bfb785a3a1cb694575e873464e77200a3fbed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
